Import('*')

# Only build TraceCPU if we have support for protobuf as TraceCPU relies on it
SimObject('TraceCPU.py', tags='protobuf')
Source('trace_cpu.cc', tags='protobuf')

DebugFlag('TraceCPUData')
DebugFlag('TraceCPUInst')
